# Site settings
title: Chad Furman - Senior Technical Lead
email: chad@chadfurman.com
description: > # this means to ignore newlines until "baseurl:"
  Specializing in building APIs and SPAs for enterprises that value security [:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://chads.website" # the base hostname & protocol for your site
twitter_username: chadfurman
github_username:  chadfurman
comments: true

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
