# Site settings
title: Chad Furman - Senior Full Stack Developer
email: chad@chadfurman.com
description: > # this means to ignore newlines until "baseurl:"
  Specializing in building REST APIs and Single-page applications in ES5/ES6/PHP. [:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chads.website" # the base hostname & protocol for your site
twitter_username: chadfurman
github_username:  ShadeLotus

# Build settings
markdown: kramdown
